#!/usr/bin/env bash

RUST_TOOLCHAIN="nightly"

set +e
git submodule update --init --recursive
pushd wallet-wasm
rustup toolchain install ${RUST_TOOLCHAIN} && \
rustup target add --toolchain ${RUST_TOOLCHAIN} wasm32-unknown-unknown && \
cargo  +${RUST_TOOLCHAIN} build --target wasm32-unknown-unknown --release --verbose && \
popd && \
npm run build
